config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :tours, only: [:index, :new, :create, :show] do
    resources :bookings, only: [:create]
    resources :reviews, only: [:create]
  end
  get '/hosted_tours', to: 'tours#hosted_tours', as: :hosted_tours
  resources :bookings, only: [:index, :update]
  resources :users, only: [:show]

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :tour

  validates :guests, numericality: { greater_than: 0 }

  def pending?
    status == 'pending'
  end

  def nice_date
    "#{start_date.day}/#{start_date.month}/#{start_date.year} at #{start_date.strftime('%H')}:#{start_date.strftime('%M')}"
  end

  enum status: [ :pending, :accepted, :rejected, :canceled]
  # scope :booked, -> { where(booked: true) }
  scope :pending, -> { where(status: :pending) }
  scope :accepted, -> { where(status: :accepted) }
  scope :rejected, -> { where(status: :rejected) }
  scope :canceled, -> { where(status: :canceled) }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :tour
  validates :comment, length: {minimum: 5}
  validates :time, presence: true

  def nice_date
    "#{time.day}/#{time.month}/#{time.year} at #{time.strftime('%H')}:#{time.strftime('%M')}"
  end
end

app/models/tour.rb
class Tour < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  validates :name, :description, :location, :price, presence: true
  validates :price, numericality: { greater_than: 0 }
  has_many_attached :photos
  has_many :reviews, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tours, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :bookings_as_host, through: :tours, source: :bookings
  validates :first_name, :last_name, presence: true
  has_one_attached :photo
  has_many :reviews, dependent: :destroy

  def full_name
    "#{first_name.capitalize} #{last_name.capitalize}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit::Authorization
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end
  
  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = policy_scope(Booking)
  end

  def new
    @booking = Booking.new
    authorize @booking
  end

  def create
    @booking = Booking.new(booking_params)
    @tour = Tour.find(params[:tour_id])
    @booking.user = current_user
    @booking.tour = @tour
    authorize @booking
    if @booking.save
      redirect_to bookings_path
    else
      @reviews = @tour.reviews
      @review = Review.new
      render "tours/show", status: :unprocessable_entity
    end
  end

  def edit
    @booking = Booking.find(params[:id])
    authorize(@booking)
  end

  def update
    @booking = Booking.find(params[:id])
    # @booking.assign_attributes(booking_params)
    @booking.status = params[:booking][:status]
    authorize(@booking)
    if @booking.update(booking_params) && @booking.status != 'canceled'
      redirect_to hosted_tours_path(tab: 'booking'), status: :see_other
    elsif !@booking.update(booking_params) && @booking.status != 'canceled'
      render :hosted_tours
    elsif @booking.update(booking_params) && @booking.status == 'canceled'
      redirect_to bookings_path, status: :see_other
    else
      render :bookings
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :user_id, :guests, :status)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
    @review = Review.new(review_params)
    @tour = Tour.find(params[:tour_id])
    @review.user = current_user
    @review.tour = @tour
    @review.time = DateTime.now
    authorize @review
    if @review.save
      redirect_to tour_path(@tour)
    else
      @reviews = @tour.reviews
      render "tours/show", status: :unprocessable_entity
    end
  end

  private

  def review_params
    params.require(:review).permit(:comment, :time)
  end
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  skip_after_action :verify_authorized, only: :hosted_tours

  def index
    @tours = Tour.all
    @tours = policy_scope(Tour)
  end

  def new
    @tour = Tour.new
  end

  def show
    @tour = Tour.find(params[:id])
    @review = Review.new
    @reviews = @tour.reviews
    authorize @tour
  end

  def create
    @tour = Tour.new(tour_params)
    @tour.user = current_user
    @tours = current_user.tours
    # All this extra stuff, bookings to rejection
    # it's there to make sure it loads on
    # the hosted_tours page
    # if it fails to save
    @bookings = policy_scope([:host, Booking])
    authorize @tour
    if @tour.save
      redirect_to :hosted_tours
    else
      @tab = 'new-tab'
      render 'hosted_tours', status: :unprocessable_entity
    end
  end

  def hosted_tours
    @tour = Tour.new
    @tours = current_user.tours
    @bookings = policy_scope([:host, Booking])
  end

  private

  def tour_params
    # in permitted params, :photos must be photos: []
    # If not file upload doesn't work!
    params.require(:tour).permit(:name, :price, :description, :location, photos: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    authorize @user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<%= simple_form_for([tour, booking]) do |f| %>
  <%= f.input :start_date, html5: true, input_hmtl: {value: DateTime.now} %>
  <%= f.input :guests, input_html: {data: {action:"change->booking#updatePrice"},min: '1', step: 'any'} %>
  <%= f.submit "Book a tour" %>
<% end %>

app/views/bookings/index.html.erb
<div class= "container">
  <h2 class="index-header">My bookings</h2>
  <div class="cards">
    <% @bookings.each do |booking| %>
      <div class="card"id="bg-image"style="background-image: url('https://images.pexels.com/photos/8892/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1');height: 60vh">
        <p id="tombstone-head"><strong><%= booking.tour.name %></strong></p>
        <div id="carouselExampleIndicators<%= booking.id %>" class="carousel slide h-50">
          <div class="carousel-indicators">
            <button type="button" data-bs-target="#carouselExampleIndicators<%= booking.id %>" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
            <% if booking.tour.photos.count > 1 %>
              <% (booking.tour.photos.count -  1).times do |i| %>
                <button type="button" data-bs-target="#carouselExampleIndicators<%= booking.id %>" data-bs-slide-to="<%=i + 1%>" aria-label="Slide <%=i + 1%>"></button>
              <% end %>
            <% end %>
          </div>
          <div class="carousel-inner  h-100">
            <% booking.tour.photos.each_with_index do |photo, index| %>
              <div class="carousel-item  h-100 my-relative <%= "active" if index == 0 %>">
                <%= cl_image_tag photo.key, class:"d-block w-100 h-100", alt:"..." %>
                <div class="favorite-logo">
                  <img src="https://cdn-icons-png.flaticon.com/512/7562/7562403.png" alt="" class="logo-size">
                </div>
                <%= link_to '', tour_path(booking.tour), class: "my-overlay" %>
              </div>
            <% end %>
          </div>
          <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators<%= booking.id %>" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators<%= booking.id %>" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
        </div>
        <div class="my relative">
          <div class="card-info-top">
            <p>$ <%= booking.tour.price * booking.guests %></p>
            <p>⚰️ 5.0</p>
          </div>
          <div class="card-info-bottom">
            <p><i class="fa-solid fa-hourglass"></i> <%= booking.status.capitalize %></p>
            <i class="fa-regular fa-clock card-product-logo-margin"></i><%= booking.nice_date %>
            <%# <%= simple_form_for booking do |f| %>
              <%# <%= f.input :status, as: :hidden, input_html: { value: 'canceled'} %>
              <%# <%= f.submit 'Cancel', class: 'btn btn-info' %>
              <%# <% end %>
              <%= link_to '', tour_path(booking.tour), class: "my-overlay" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HauntedTours</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/pages/home.html.erb
  <%= render 'shared/banner' %>
<div class="container-fluid d-flex justify-content-evenly m-0 p-0 pt-3" style="background-color:black">
  <div class="card3">
    <h3>About Us</h3>
    <p>We're here and ready to bring the fear! Haunted tours Japan is your one stop shop for all things horrific sight-seeing! Come join us as a customer, and tour the famous
      locales of Japan. Journey to haunted samurai battlefields, yuki-onna infested mountain resorts, graveyards of the damned, and even
      the sewer hideouts of serial killers! Rather be a host, than hosted? Sign up and lead some neer-do-wells and neer-do-evils around as
      a guide! Load up your haunted tour and itinerary, and let's get scaring!</p>
  </div>
</div>

app/views/reviews/_new.html.erb
<%= simple_form_for([tour, review], data: {
  action: 'submit->insert-in-list#submit'}) do |f| %>
  <%= f.input :comment, label: 'Comment' %>
  <%= f.button :submit, class: 'create-review'%>
<% end %>

app/views/reviews/_review.html.erb
<p class="m-5">
  <i class="fa-solid fa-quote-left fa-2x"></i>
  <%= review.comment %>
</p>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://res.cloudinary.com/dfjkxrkvj/image/upload/v1676965338/jessica-rigollot-uMpAhrKpUCg-unsplash_g4ng7l.jpg);">
  <div class="container d-flex justify-content-center" style="margin-right:auto;margin-left:auto">
    <div style="text-align:start">
      <h1>Have the fright <strong>of your Life</strong> at <strong>Haunted Tours</strong>!</h1>
      <p>Experience the greatest, most horrific tours of Japan.</p>
      <%= button_to "See our Haunted Tours", tours_path, class:"btn btn-danger rounded", method: :get %>
    </div>
  </div>
</div>

app/views/shared/_bookings-status.html.erb
<% bookings.each do |booking|%>
  <div class="card-product">
    <%= cl_image_tag booking.user.photo.key, class:'rounded-circle'%>
    <div class="card-product-infos black-shadow">
      <h3 class = "black-shadow"><%= booking.user.full_name %></h3>
      <div class="d-flex align-items-end card-product-bottom-height">
        <div class="card-product-margin my-relative ">
          <i class="fa-regular fa-building card-product-logo-margin"></i> <%= booking.tour.name %>
          <%= link_to '', tour_path(booking.tour), class: "my-overlay" %>
        </div>
        <div class="card-product-margin ">
          <i class="fa-regular fa-clock card-product-logo-margin"></i><%= booking.nice_date %>
        </div>
        <div class="card-product-margin">
          <i class="fa-solid fa-person"></i>
          <%= booking.guests %>
        </div>
        <div class="card-product-margin">
          <i class="fa-regular fa-dollar-sign "></i>
          <%= booking.tour.price * booking.guests  %>
        </div>
        <div class="d-flex">
          <% if booking.pending? %>
            <%= simple_form_for booking do |f| %>
              <%= f.input :status, as: :hidden, input_html: {value: 'accepted'} %>
              <%= f.submit 'Accept', class: 'btn btn-info' %>
            <% end %>
            <%= simple_form_for booking do |f| %>
              <%= f.input :status, as: :hidden, input_html: {value: 'rejected'} %>
              <%= f.submit 'Reject', class: 'btn btn-light' %>
            <% end %>
          <% else %>
            <div class=""><%= booking.status %></div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_form-tour.html.erb
<%= simple_form_for tour do |f| %>
  <%= f.input :name, label: 'Tour name', error: "Tour's must have a name!" %>
  <%= f.input :price, label: "Price in Dollars", error: "Tour's must have a price!", input_html:{min: '1', step: 'any'} %>
  <%= f.input :description, label: "Describe your tour", error: "Tours must have a description!" %>
  <%= f.input :location, label: "Location of your tour", error: "Tours must have a location!" %>
  <%= f.input :photos, as: :file, input_html: { multiple: true, class: 'black-shadow'}, label: "Upload as many files as you want, select with ctrl for windows, cmd for Mac!" %>
  <%= f.button :submit, class: 'btn btn-danger'%>
<% end %>

app/views/shared/_my_tours.html.erb
<div class='container'>
  <h1 class='p-5 d-flex justify-content-center'>Your hosted tours</h1>
  <div class="cards">
    <% @tours.each do |tour| %>
      <div class="card"id="bg-image"style="background-image: url('https://images.pexels.com/photos/8892/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1');height: 60vh">
        <p id="tombstone-head"><strong><%= tour.name %></strong></p>
        <div id="carouselExampleIndicators<%= tour.id %>" class="carousel slide h-50">
          <div class="carousel-indicators">
            <button type="button" data-bs-target="#carouselExampleIndicators<%= tour.id %>" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
            <% if tour.photos.count > 1 %>
              <% (tour.photos.count -  1).times do |i| %>
                <button type="button" data-bs-target="#carouselExampleIndicators<%= tour.id %>" data-bs-slide-to="<%=i + 1%>" aria-label="Slide <%=i + 1%>"></button>
              <% end %>
            <% end %>
          </div>
          <div class="carousel-inner h-100">
            <% tour.photos.each_with_index do |photo, index| %>
              <div class="favorite-logo" >
                <img src="https://cdn-icons-png.flaticon.com/512/7562/7562403.png" alt="" class="logo-size">
              </div>
              <div class="carousel-item h-100 my-relative <%= "active" if index == 0 %>">
                <%= cl_image_tag photo.key, class:"d-block w-100 h-100", alt:"..." %>
                <%= link_to '', tour_path(tour), class: "my-overlay" %>
              </div>
            <% end %>
          </div>
          <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators<%= tour.id %>" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators<%= tour.id %>" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
        </div>
        <div class="my-relative">
          <div class="card-info-bottom">
            <p>⚰️ 5.0</p>
            <p><i class="fa-regular fa-building"></i> <%= tour.location %></p>
            <p>$ <%= tour.price %></p>
            <%= link_to '', tour_path(tour), class: "my-overlay" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://www.svgrepo.com/show/187699/ghost.svg" %>
    <% end %>
    <h2 class="min-max-content">Haunted Tours</h2>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active min-max-content">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item active min-max-content">
            <%= link_to "Tours", tours_path, class: "nav-link" %>
          </li>
          <li class="nav-item active min-max-content">
            <%= link_to "My Bookings", bookings_path, class: "nav-link" %>
          </li>
          <li class="nav-item active min-max-content">
            <%= link_to "My Hosted Tours", hosted_tours_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://www.svgrepo.com/show/407756/zombie.svg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Messages", "#", class: "dropdown-item" %>
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_review_display_all.html.erb
<% reviews.order('time DESC').each do |review| %>
  <div class='review' id="bg-image-show"style="margin=8px; padding= 8px; background-image: url('https://images.pexels.com/photos/8892/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1');">
    <h4><%= review.user.first_name %></h4>
    <p>Posted:<%= review.nice_date %></p>
    <p><%= review.comment %></p>
  </div>
<% end %>

app/views/shared/_reviews.html.erb
<%= simple_form_for([tour, review]) do |f| %>
  <%= f.input :comment, label: 'Comment', error: "20 or more characters required!" %>
  <%= f.button :submit, class: 'create-review'%>
<% end %>

app/views/tours/_show.html.erb
<div class='container'>
  <div class='p-5 ms-5 text-light'>
    <h1><%= @tour.name %></h1>
    <h5>
    </h5>
  </div>
  <div class='photo-gallery' data-controller="lightbox">
    <% @tour.photos.each.with_index do |photo, index| %>
      <%= link_to url_for(photo), class: "#{"big-one" if index == 0}" do %>
        <%= cl_image_tag photo.key, class: "w-100", style: "#{"height: 250px" unless index == 0}" %>
      <% end %>
    <% end %>
  </div>
</div>
<div class='tour-content'>
  <div class='container d-flex justify-content-between w-100 p-4'>
    <div class='mb-3 w-75 pe-5'>
      <div class='show-tour-content p-3' id="bg-image-show"style="background-image: url('https://images.pexels.com/photos/8892/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1');height: 20vh">
        <h3 class="white-shadow">Tour hosted by: <%=@tour.user.first_name  %>
        </h3>
        <span class="white-shadow">Location: <%=  @tour.location %></span>
      </div>
      <div class='show-tour-content p-3 mt-4 p-3 mt-5 h-50 d-flex flex-column justify-content-center' id="bg-image-show"style="background-image: url('https://images.pexels.com/photos/8892/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1');height: 20vh">
        <h2 class='white-shadow'>Tour description</h2>
        <p><%= @tour.description %></p>
      </div>
    </div>
    <div class='show-tour-content p-3' data-controller="booking" id="bg-image-show"style="background-image: url('https://images.pexels.com/photos/8892/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1');height: 60vh">
      <h3 class="white-shadow" >$<span data-booking-target="price" data-value= <%=@tour.price%>><%= @tour.price %></span></h3>
        <div class="dropdown" >
          <%# <button class="btn btn-info dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            Victims number:
          </button> %>
          <div>
            <%= render 'bookings/form', tour: @tour, booking: Booking.new %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class='review d-flex mt-3'>
    <div class='review-form w-75 d-flex justify-content-center'>
      <div class='w-75'>
        <%= render 'shared/reviews', tour: @tour, review: @review %>
        <div class='pt-4'>
          <%= render 'shared/review_display_all', reviews: @reviews %>
        </div>
      </div>
    </div>
  </div>

app/views/tours/_show2.html.erb
<div class='container'>
  <div class='py-3 px-5 ms-5 text-light text-center'>
    <h1><%= @tour.name %></h1>
  </div>
  <div class='row'>
    <div class='col-6 justify-content-start'>
      <%# <div class='justify-content-start'> %>
        <div class='photo-gallery-2' data-controller="lightbox">
          <% @tour.photos.each.with_index do |photo, index| %>
            <%= link_to url_for(photo), class: "#{"big-one-2" if index == 0}" do %>
              <%= cl_image_tag photo.key, class: "w-100 #{"small-one-#{index}" if index > 0}"%>
            <% end %>
          <% end %>
        </div>
      <%# </div> %>
    </div>
    <div class='col-6 tour-content'>
      <%# <div class='tour-content'> %>
        <div class='mb-3'>
          <div class='row align-items-start w-100 mb-4'>
              <div class='show-tour-content p-3' id="bg-image-show"style="background-image: url('https://images.pexels.com/photos/8892/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1')">
                <h3 class='white-shadow'>Tour hosted by: <%=@tour.user.first_name  %></h3>
                <span class='white-shadow'>Location: <%=@tour.location %></span>
              </div>
          </div>
          <div class='row h-50 my-4 w-100'>
              <div class='show-tour-content p-3 p-3 h-50 id="bg-image-show'style="background-image: url('https://images.pexels.com/photos/8892/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1')">
                <h2 class='white-shadow'>Tour description</h2>
                <p class='white-shadow'><%= @tour.description %></p>
              </div>
          </div>
          <div class='row my-4 justify-content-center'>
            <div class='show-tour-content p-3 h-20 w-75' data-controller="booking" id="bg-image-show"style="background-image: url('https://images.pexels.com/photos/8892/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1')">
              <h3 class="white-shadow" >$<span data-booking-target="price" data-value= <%=@tour.price%>><%= @tour.price %></span></h3>
              <div class="dropdown">
              <%# <button class="btn btn-info dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
              Victims number:
              </button> %>
                <div>
                  <%= render 'bookings/form', tour: @tour, booking: Booking.new %>
                </div>
              </div>
            </div>
          </div>
        </div>
      <%# </div> %>
    </div>
  </div>
  <div class='row justify-content-center'>
    <div class="col">
      <div class='review mt-3'>
        <div class='review-form w-75'>
          <div class='w-75'>
            <%= render 'shared/reviews', tour: @tour, review: @review %>
            <div class='pt-4'>
              <%= render 'shared/review_display_all', reviews: @reviews %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tours/show.html.erb
<div class='container'>
  <%= render 'show' %>
</div>